### ISSUE TITLE
Front-end Design

### ISSUE THREAD

**Issue by marupoix** [massachusetts-of-ctu/glennard-activity#5]
- [x] Login

> - [ ] Animation

- [x] Register

> - [ ] Animation

- [x] Dashboard

**Comment by rondinabrybry** [comment]
Done nako sa dashboard

**Comment by marupoix** [comment]
ok na sad ko sa design sa login ug register, naa lay error sa hide password pa help niya ko sa javascript ani

**Comment by rondinabrybry** [comment]
Okay na ang javascript. all goods. Proceed to responsive na
