### ISSUE TITLE
Merge

### ISSUE THREAD

**Issue by marupoix** [massachusetts-of-ctu/glennard-activity#7]
Need na nato i merge ang mga code nga gi design sa login, register, dashboard. Including na ang pag limpyo sa back-end ug ang pag sort sa mga folder para hapsay ang atong document.

Objectives:

- [x] Merge the designed login with the back-end
- [x] Merge the designed register with the back-end
- [x] Link the dashboard with the designed login and register
- [x] Remove unecessary php, css files

**Comment by rondinabrybry** [comment]
Done all
