### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by marupoix** [massachusetts-of-ctu/glennard-activity#8]
Ipa responsive niya ko ni ang login, register ug dashboard.

- [x] Login
- [x] Register
- [x] Dashboard

**Comment by rondinabrybry** [comment]
kumusta ni @makRobol

**Comment by makRobol** [comment]
Mao rani nakayas akung powers, Sa dashboard rani
[Main_html.txt](https://github.com/massachusetts-of-ctu/glennard-activity/files/13060578/Main_html.txt)
[test.css.txt](https://github.com/massachusetts-of-ctu/glennard-activity/files/13060581/test.css.txt)

**Comment by rondinabrybry** [comment]
done na nako ang login and register
